[package]

name = "time"
version = "0.1.2"
authors = ["The Rust Project Developers"]
build = "build.rs"
license = "MIT/Apache-2.0"
homepage = "https://github.com/rust-lang/time"
repository = "https://github.com/rust-lang/time"
documentation = "http://doc.rust-lang.org/time"
description = """
Utilities for working with time-related functions in Rust.
"""

[build-dependencies.gcc]
git = "https://github.com/servo/gcc-rs"
branch = "servo"
